### ISSUE TITLE
Missing symbols when loading pbdBASE: `pdtrmr2d_`

### ISSUE THREAD

**Issue by ehiggs** [wrathematics/pbdBASE#22] opened 2015-05-28 11:50 UTC
I'm using icc and impi (Intel MPI) and trying to wrap the pbd system's install for [EasyBuild](http://easybuild.readthedocs.org/en/latest/).

When trying to install `pbdBASE` I get an error that `pdtmr2d_` is not defined. I can work around this by patching the configure script to link in my ScaLAPACK libraries. 

@snoweye suggested that if we have our own ScaLAPACK libraries installed we don't need pbdSLAP installed, but since it's a dependency of pbdBASE, we do indeed need it (afaik). I'm not aware of a concept of optional dependencies in R.

I guess the fix would either be to get pbdSLAP to have a configure option that links in all the ScaLAPACK libraries I give it so the rest of the pbd packages all work with no alterations.

**Comment by wrathematics** [comment] 2015-05-28 12:05
Hi, thanks for the report.

We've had mixed success in the past with mkl/icc/ifort/impi.  The most trouble is with accelerator cards (xeon phi), and as far as I can tell, the problem lies with Intel on that one.

You do indeed need pbdSLAP installed, but it is possible to link it with a different ScaLAPACK library.  So you don't need to build the (netlib) distribution of ScaLAPACK that we ship in pbdSLAP.  This process is described in section 2.2 of the [pbdSLAP vignette](https://github.com/RBigData/pbdSLAP/blob/master/inst/doc/pbdSLAP-guide.pdf).  We've done this a few times, but generally work on machines without MKL, so it historically hasn't been a big priority for us.  Given that R requires pbdSLAP, I would recommend this route over patching pbdBASE, since it will save a lot of build time.

If you get a chance to try, please let us know if that works or not.

**Comment by snoweye** [comment] 2015-05-29 00:58
You still need pbdSLAP to be installed, but you allow to ask it to configure/save the link to external ScaLAPACK. Basically, pbdSLAP has no real function in run time. All pbd* package works best with GNU autoconfig and automake as used by R. If you have your own version, then the problem is probably some subdirectories did not compile/link correctly. Please let us know if by chance it works.

**Comment by ehiggs** [comment] 2015-06-01 11:46
Thanks you lot. I got past the configuration and now I'm trying to link. Unfortunately, `pbdBASE` appears to depend on a symbol in a ScaLAPACK which isn't in a particular interface: [`BI_COMM_WORLD`](http://www.netlib.org/scalapack/explore-html/d1/d7f/_b_i___global_vars_8c.html). It's not available in the Intel implementation of ScaLAPACK.

Do you use `BI_COMM_WORLD` or `sizeof(BLACS_APTS)`? If not, maybe I can patch it with an `#ifdef. They only seem to appear in `src/export_blacs/pkg_tools.c`:

```c
        /* These are only saw by new pakcages. */
        BLACS_APTS.BI_MaxNCtxt = &BI_MaxNCtxt;
        BLACS_APTS.BI_MaxNSysCtxt = &BI_MaxNSysCtxt;
        BLACS_APTS.BI_Iam = &BI_Iam;
        BLACS_APTS.BI_Np = &BI_Np;
        BLACS_APTS.BI_ReadyB = BI_ReadyB;
        BLACS_APTS.BI_ActiveQ = BI_ActiveQ;
        BLACS_APTS.BI_AuxBuff = &BI_AuxBuff;
        BLACS_APTS.BI_MyContxts = BI_MyContxts;
        BLACS_APTS.BI_SysContxts = BI_SysContxts;
        BLACS_APTS.BI_COMM_WORLD = BI_COMM_WORLD;
        BLACS_APTS.BI_Stats = BI_Stats;
```

**Comment by wrathematics** [comment] 2015-06-01 16:50
Interesting, thanks for looking into this.  @snoweye is our Make* expert, so I will ultimately have to defer to him on that.  But I believe it's not used by us and could be hidden if something like `__INTEL_COMPILER` is defined.

**Comment by ehiggs** [comment] 2015-06-03 11:27
I got it working on intel (icc + impi) and I was able to run the `iris_gdb.r` demo program so I think it's working. Is there a test suite to make sure everything is working appropriately aside from just running the demos?

If you're interested, I submitted the scripts to the EasyBuild project [here](https://github.com/hpcugent/easybuild-easyblocks/pull/620) and [here](https://github.com/hpcugent/easybuild-easyconfigs/pull/1659). My intel patch is [here](https://github.com/ehiggs/easybuild-easyconfigs/blob/pbd/easybuild/easyconfigs/r/R-bundle/Ignore-BI_COMM_GLOBAL-on-intel.patch).

**Comment by wrathematics** [comment] 2015-06-14 22:29
Fixed in https://github.com/wrathematics/pbdBASE/commit/dfd07b237c97aab423fabffa083905de37170cd0

**Closed by wrathematics** 2015-06-14 22:29 UTC
